version: '3'

services:

  app:
    build:
      context: node
    container_name: app
    command: >
        bash -c "npm install express && node index.js"
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s docker-entrypoint.sh
    networks:
      - node-network
    volumes:
      - ./node:/usr/src/app
    tty: true
    depends_on:
       - db
    restart: always

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
      - ./database:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_DATABASE=DB_DESAFIO
      - MYSQL_ROOT_PASSWORD=root
      - LANG=C.UTF-8
      - TZ=America/Sao_Paulo
    networks:
      - node-network

  nginx:
    build:
      context: nginx
    ports:
      - "8080:80"
      - "3000:80"
    depends_on:
      - app
    networks:
      - node-network
    restart: always


networks:
  node-network:
    driver: bridge
